story:
  path: story/{title}
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Story\Controller\PageFactory::viewStory
    _type: MyTravel\Story\Model\Story
    _format: html
    title:

