timeline:
  path: timeline/{title}
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Timeline\Controller\PageFactory::viewTimeline
    _type: MyTravel\Timeline\Model\TimelineItem
    _format: html
    title:
timelineapi:
  path: api/timeline/{offset}/{length}/{extra}
  methods: GET
  schemes: https
  defaults: 
    _controller: MyTravel\Core\Controller\ItemController::output
    _format: json
    _type: MyTravel\Timeline\Model\TimelineItem
    offset: 0
    length: 10
    extra:
legacyimport:
  path: api/import/timeline/legacy
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Timeline\Controller\TimelineItemController::importLegacyData