environment: dev
basepath: /
directories:
  files: files
  images: files/images
  themes: themes
theme: default
database:
  connections:
    sqlite:
      driver: sqlite
      directory: db-sqlite
      name: mytravel
routing:
  routes:
    home:
      path: ''
      method: GET
      callback: [MyTravel\Core\Controller\Page, viewHomePage]
    about:
      path: about
      method: GET
      callback: [MyTravel\Core\Controller\Page, viewAboutPage]
    imgeditlist:
      path: edit/image
      method: GET
      callback: [MyTravel\Core\Controller\Page, viewEditImagePage]
    imagefile:
      path: img/[*:title]/[**:trailing]?
      method: GET
      callback: [MyTravel\Core\Controller\Image, viewImage]
    jsbundle:
      path: js/bundle
      method: GET
      callback: [MyTravel\Core\Controller\Js, viewJsBundle]
    cssbundle:
      path: css/bundle
      method: GET
      callback: [MyTravel\Core\Controller\Css, viewCssBundle]
  
