home:
  path: ''
  methods: GET
  schemes: https
  defaults: 
    _controller: MyTravel\Core\Controller\PageFactory::viewHomePage
    _format: html
about:
  path: about
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Core\Controller\PageFactory::viewAboutPage
    _format: html
item:
  path: item/{title}
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Core\Controller\PageFactory::viewItemPage
    _format: html
    _type: MyTravel\Core\Model\Item
    title:
img:
  path: img/{title}/{trailing}
  methods: GET
  schemes: https
  defaults: 
    _controller: MyTravel\Core\Controller\Image::view
    _format: image/*
    _type: MyTravel\Core\Model\Item
    trailing:
itemapi:
  path: api/item/{offset}/{length}
  methods: GET
  schemes: https
  defaults: 
    _controller: MyTravel\Core\Controller\ItemController::output
    _format: json
    _type: MyTravel\Core\Model\Item
    offset: 0
    length: 10
itemcreate:
  path: api/item
  methods: POST
  schemes: https
  defaults:
    _controller: MyTravel\Core\Controller\ItemController::create
    _format: json
    _type: MyTravel\Core\Model\Item
itemupdate:
  path: api/item/{id}
  methods: PUT
  schemes: https
  defaults: 
    _controller: MyTravel\Core\Controller\ItemController::update
    _format: json
    _type: MyTravel\Core\Model\Item
itemdelete:
  path: api/item/{id}
  methods: DELETE
  schemes: https
  defaults: 
    _controller: MyTravel\Core\Controller\ItemController::delete
    _format: json
    _type: MyTravel\Core\Model\Item
jsbundle:
  path: js/bundle
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Core\Controller\Js::viewJsBundle
    _format: js
cssbundle:
  path: css/bundle
  methods: GET
  schemes: https
  defaults:
    _controller: MyTravel\Core\Controller\Css::viewCssBundle
    _format: css
