home:
  path: ''
  methods: GET
  schemes: https
  defaults: { _controller: MyTravel\Core\Controller\PageFactory::viewHomePage }
about:
  path: about
  methods: GET
  schemes: https
  defaults: { _controller: MyTravel\Core\Controller\PageFactory::viewAboutPage }
imgeditlist:
  path: edit/image/{id}
  methods: GET
  schemes: https
  defaults: { _controller: MyTravel\Core\Controller\PageFactory::viewEditImagePage, id: }
imgfileview:
  path: img/{title}/{trailing}
  methods: GET
  schemes: https
  defaults: { _controller: MyTravel\Core\Controller\Image::viewImage, trailing: }
jsbundle:
  path: js/bundle
  methods: GET
  schemes: https
  defaults: { _controller: MyTravel\Core\Controller\Js::viewJsBundle }
cssbundle:
  path: css/bundle
  methods: GET
  schemes: https
  defaults: { _controller: MyTravel\Core\Controller\Css::viewCssBundle }
